### ISSUE TITLE
Solvent viscosity

### ISSUE THREAD

**Issue by sottcap** [stochasticHydroTools/PSE#5]
Hi,

I am curious about how we can adjust solvent viscosity in the code. I investigated the code quite carefully but I couldn't find that part. Should we just assume the solvent viscosity, eta, equal to the unity? Originally, I thought \eta is the solvent viscosity but it seems gaussian split parameters for SE. Please advise me. Thank you in advance!

**Comment by andrew-fiore** [comment]
The parameter \eta is indeed the Ewald splitting parameter for the spectral Ewald method. As is standard, the simulations works in dimensionless units, where the mobility tensor is non-dimensionalized by the Stokes drag, 6*pi*(viscosity)*(radius). So for a single particle, applying a unit force results in a unit velocity.
