### ISSUE TITLE
Multiple GPUs using MPI

### ISSUE THREAD

**Issue by dmrobe001** [stochasticHydroTools/PSE#6]
The installation instructions for this module recommend installing HOOOMD with the flag:

-DENABLE_MPI=ON

I don't see any mention of MPI in for the installation of this plugin, though. Can this plugin use MPI to spread a single system across multiple GPUs?

Thank you

**Comment by andrew-fiore** [comment]
The plugin was written to only leverage a single GPU, so there's currently no support for multiple GPU processing.
